/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "JjfsCache"
 * 	found in "../jjfs_cache.asn1"
 */

#include "JjfsDir.h"

static asn_TYPE_member_t asn_MBR_files_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_JjfsFile,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_files_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_files_specs_4 = {
	sizeof(struct files),
	offsetof(struct files, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_files_4 = {
	"files",
	"files",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_files_tags_4,
	sizeof(asn_DEF_files_tags_4)
		/sizeof(asn_DEF_files_tags_4[0]), /* 1 */
	asn_DEF_files_tags_4,	/* Same as above */
	sizeof(asn_DEF_files_tags_4)
		/sizeof(asn_DEF_files_tags_4[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_files_4,
	1,	/* Single element */
	&asn_SPC_files_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_subdirs_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_JjfsDir,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_subdirs_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_subdirs_specs_6 = {
	sizeof(struct subdirs),
	offsetof(struct subdirs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_subdirs_6 = {
	"subdirs",
	"subdirs",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_subdirs_tags_6,
	sizeof(asn_DEF_subdirs_tags_6)
		/sizeof(asn_DEF_subdirs_tags_6[0]), /* 1 */
	asn_DEF_subdirs_tags_6,	/* Same as above */
	sizeof(asn_DEF_subdirs_tags_6)
		/sizeof(asn_DEF_subdirs_tags_6[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_subdirs_6,
	1,	/* Single element */
	&asn_SPC_subdirs_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_JjfsDir_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct JjfsDir, name),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct JjfsDir, size),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"size"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct JjfsDir, files),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_files_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"files"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct JjfsDir, subdirs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_subdirs_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subdirs"
		},
};
static const ber_tlv_tag_t asn_DEF_JjfsDir_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_JjfsDir_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* size */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 0, 0, 0 }, /* name */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 1 }, /* files */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 0 } /* subdirs */
};
static asn_SEQUENCE_specifics_t asn_SPC_JjfsDir_specs_1 = {
	sizeof(struct JjfsDir),
	offsetof(struct JjfsDir, _asn_ctx),
	asn_MAP_JjfsDir_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_JjfsDir = {
	"JjfsDir",
	"JjfsDir",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_JjfsDir_tags_1,
	sizeof(asn_DEF_JjfsDir_tags_1)
		/sizeof(asn_DEF_JjfsDir_tags_1[0]), /* 1 */
	asn_DEF_JjfsDir_tags_1,	/* Same as above */
	sizeof(asn_DEF_JjfsDir_tags_1)
		/sizeof(asn_DEF_JjfsDir_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_JjfsDir_1,
	4,	/* Elements count */
	&asn_SPC_JjfsDir_specs_1	/* Additional specs */
};

