/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "JjfsCache"
 * 	found in "jjfs_cache.asn1"
 */

#include "JjfsDir.h"

static asn_TYPE_member_t asn_MBR_files_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_JjfsFile,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_files_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_files_specs_3 = {
	sizeof(struct files),
	offsetof(struct files, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_files_3 = {
	"files",
	"files",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_files_tags_3,
	sizeof(asn_DEF_files_tags_3)
		/sizeof(asn_DEF_files_tags_3[0]), /* 1 */
	asn_DEF_files_tags_3,	/* Same as above */
	sizeof(asn_DEF_files_tags_3)
		/sizeof(asn_DEF_files_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_files_3,
	1,	/* Single element */
	&asn_SPC_files_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_subdirs_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_JjfsDir,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_subdirs_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_subdirs_specs_5 = {
	sizeof(struct subdirs),
	offsetof(struct subdirs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_subdirs_5 = {
	"subdirs",
	"subdirs",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_subdirs_tags_5,
	sizeof(asn_DEF_subdirs_tags_5)
		/sizeof(asn_DEF_subdirs_tags_5[0]), /* 1 */
	asn_DEF_subdirs_tags_5,	/* Same as above */
	sizeof(asn_DEF_subdirs_tags_5)
		/sizeof(asn_DEF_subdirs_tags_5[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_subdirs_5,
	1,	/* Single element */
	&asn_SPC_subdirs_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_JjfsDir_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct JjfsDir, name),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct JjfsDir, files),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_files_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"files"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct JjfsDir, subdirs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_subdirs_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subdirs"
		},
};
static const ber_tlv_tag_t asn_DEF_JjfsDir_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_JjfsDir_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* files */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 }, /* subdirs */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 0, 0, 0 } /* name */
};
static asn_SEQUENCE_specifics_t asn_SPC_JjfsDir_specs_1 = {
	sizeof(struct JjfsDir),
	offsetof(struct JjfsDir, _asn_ctx),
	asn_MAP_JjfsDir_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_JjfsDir = {
	"JjfsDir",
	"JjfsDir",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_JjfsDir_tags_1,
	sizeof(asn_DEF_JjfsDir_tags_1)
		/sizeof(asn_DEF_JjfsDir_tags_1[0]), /* 1 */
	asn_DEF_JjfsDir_tags_1,	/* Same as above */
	sizeof(asn_DEF_JjfsDir_tags_1)
		/sizeof(asn_DEF_JjfsDir_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_JjfsDir_1,
	3,	/* Elements count */
	&asn_SPC_JjfsDir_specs_1	/* Additional specs */
};

